"""Initial schema - v1.0.0

Creates all base tables for the Managed Nebula platform:
- Certificate Authority management
- Client configuration and tokens
- IP pool allocation and assignments
- Firewall rules and rulesets
- Group hierarchies and permissions
- User management and authentication
- Global settings

Revision ID: fd03ead652bc
Revises: 
Create Date: 2025-11-09 19:53:41.025965
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fd03ead652bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pem_cert', sa.LargeBinary(), nullable=False),
    sa.Column('pem_key', sa.LargeBinary(), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_previous', sa.Boolean(), nullable=False),
    sa.Column('can_sign', sa.Boolean(), nullable=False),
    sa.Column('include_in_config', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ca_certificates_name'), 'ca_certificates', ['name'], unique=False)
    op.create_table('firewall_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('port', sa.String(length=100), nullable=False),
    sa.Column('proto', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('cidr', sa.String(length=100), nullable=True),
    sa.Column('local_cidr', sa.String(length=100), nullable=True),
    sa.Column('ca_name', sa.String(length=100), nullable=True),
    sa.Column('ca_sha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firewall_rulesets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lighthouse_enabled', sa.Boolean(), nullable=False),
    sa.Column('lighthouse_port', sa.Integer(), nullable=False),
    sa.Column('lighthouse_hosts', sa.String(length=2000), nullable=False),
    sa.Column('default_groups', sa.String(length=2000), nullable=False),
    sa.Column('default_firewall_rules', sa.String(length=5000), nullable=False),
    sa.Column('default_cidr_pool', sa.String(length=64), nullable=False),
    sa.Column('punchy_enabled', sa.Boolean(), nullable=False),
    sa.Column('client_docker_image', sa.String(length=500), nullable=False),
    sa.Column('server_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cidr')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('ip_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_ip', sa.String(length=64), nullable=False),
    sa.Column('end_ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['ip_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruleset_rules',
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['firewall_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruleset_id'], ['firewall_rulesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ruleset_id', 'rule_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_lighthouse', sa.Boolean(), nullable=False),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('last_config_download_at', sa.DateTime(), nullable=True),
    sa.Column('config_last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pem_cert', sa.String(length=10000), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('issued_for_ip_cidr', sa.String(length=64), nullable=True),
    sa.Column('issued_for_groups_hash', sa.String(length=64), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_firewall_rulesets',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('firewall_ruleset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firewall_ruleset_id'], ['firewall_rulesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'firewall_ruleset_id')
    )
    op.create_table('client_groups',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'group_id')
    )
    op.create_table('client_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_download_config', sa.Boolean(), nullable=False),
    sa.Column('can_view_token', sa.Boolean(), nullable=False),
    sa.Column('can_download_docker_config', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_tokens_token'), 'client_tokens', ['token'], unique=True)
    op.create_table('firewall_rule_groups',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['firewall_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'group_id')
    )
    op.create_table('group_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.Column('can_add_to_client', sa.Boolean(), nullable=False),
    sa.Column('can_remove_from_client', sa.Boolean(), nullable=False),
    sa.Column('can_create_subgroup', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('ip_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ip_group_id'], ['ip_groups.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['ip_pools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('user_group_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_memberships')
    op.drop_table('ip_assignments')
    op.drop_table('group_permissions')
    op.drop_table('firewall_rule_groups')
    op.drop_index(op.f('ix_client_tokens_token'), table_name='client_tokens')
    op.drop_table('client_tokens')
    op.drop_table('client_permissions')
    op.drop_table('client_groups')
    op.drop_table('client_firewall_rulesets')
    op.drop_table('client_certificates')
    op.drop_table('user_groups')
    op.drop_table('groups')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ruleset_rules')
    op.drop_table('ip_groups')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('ip_pools')
    op.drop_table('global_settings')
    op.drop_table('firewall_rulesets')
    op.drop_table('firewall_rules')
    op.drop_index(op.f('ix_ca_certificates_name'), table_name='ca_certificates')
    op.drop_table('ca_certificates')
    # ### end Alembic commands ###
